In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('/home/ndo/bash_output/data_labels/varscan_labels.csv', sep=",", encoding='utf-8')
df

Unnamed: 0                         0  \
0                 0        chr1:783075-783276   
1                 1        chr1:784760-784961   
2                 2        chr1:785317-785518   
3                 3        chr1:797292-797493   
4                 4        chr1:803946-804147   
...             ...                       ...   
5975095     1071867  chr9:138216261-138216462   
5975096     1071868  chr9:138216453-138216654   
5975097     1071869  chr9:138217346-138217547   
5975098     1071870  chr9:138217346-138217547   
5975099     1071871  chr9:138221825-138222026   

                                                         1  labels01  \
0        ACTTACATGACCGACATGGTATTTTTATTTGGCAGCGCTGCTCTAA...         0   
1        GAAATGAGATATTTATGTAGTCTTAAGGTATCTTCTCACAAATTAT...         0   
2        GGGTGACAGGGCATTATATCAGCCACTTATCAACAAACATTTCAGA...         0   
3        ACTTTGCTCAATCTTCGCCTTTGGGTTCCTTTAGGTTTATAATGAA...         0   
4        TTAGAGGTAACTTTGCTGAACTTGTGAAGAATGGTGTGCAAGGTCC...         0   
...                                                    ...       ...   
5975095  CCCATGGCAGTGCGACAGCTGCTTCTTGGCAACTCCACCATGATCA...         1   
5975096  TGAATGTTGACAGCACAGGAATCAGGTCATACGGCCCTCCCATCTC...         1   
5975097  AGATTCAGGGCCTGCCCAGGGGCAGAGTGCCCCCAGGACTCGCCCT...         1   
5975098  AGATTCAGGGCCTGCCCAGGGGCAGAGTGCCCCCAGGACTCGCCCT...         1   
5975099  GCTCTTAGGGTGGCCCCTAAGTGAGGCTCCTCAGTGGCTCCAGCTA...         1   

         labels012  
0                0  
1                0  
2                0  
3                0  
4                0  
...            ...  
5975095          2  
5975096          2  
5975097          2  
5975098          2  
5975099          2  

[5975100 rows x 5 columns]

In [ ]:
# from sklearn.model_selection import train_test_split

# # Assuming 'data' contains your dataset and 'labels' contain corresponding labels

# # Splitting the data into 80% training and 20% test/validation combined
# X_train, X_test_val, y_train, y_test_val = train_test_split(df['1'], df['labels01'], test_size=0.2, random_state=42)

# # Splitting the test/validation data into 50% test and 50% validation
# X_test, X_val, y_test, y_val = train_test_split(X_test_val, y_test_val, test_size=0.5, random_state=42)

# print("Training set size:", len(X_train))
# print("Validation set size:", len(X_val))
# print("Test set size:", len(X_test))

X_train = df['1']
Y_train = df['labels01']


In [5]:
# Define a mapping of nucleotides to one-hot vectors
nucleotide_mapping = {
    'A': [1, 0, 0, 0],
    'C': [0, 1, 0, 0],
    'G': [0, 0, 1, 0],
    'T': [0, 0, 0, 1]
}

# Function to one-hot encode a DNA sequence
def one_hot_encode(sequence):
    encoding = np.array([nucleotide_mapping[n] for n in sequence]).astype('int8')
    return encoding

# Apply one-hot encoding to the DNA sequences
encoded_sequences = X_train.apply(one_hot_encode)



In [6]:
encoded_sequences.shape

(4780080,)

In [7]:
encoded_sequences = np.stack(encoded_sequences)
encoded_sequences

array([[[0, 0, 1, 0],
        [0, 0, 0, 1],
        [0, 0, 0, 1],
        ...,
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1]],

       [[1, 0, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 1],
        ...,
        [0, 1, 0, 0],
        [1, 0, 0, 0],
        [0, 1, 0, 0]],

       [[0, 0, 1, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        ...,
        [0, 1, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 1]],

       ...,

       [[0, 1, 0, 0],
        [0, 1, 0, 0],
        [1, 0, 0, 0],
        ...,
        [0, 1, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0]],

       [[0, 1, 0, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        ...,
        [0, 0, 1, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 1]],

       [[1, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 0, 1],
        ...,
        [0, 1, 0, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0]]], dtype=int8)

In [ ]:
# %%time
# # one-hot encode labels
# from sklearn.preprocessing import OneHotEncoder

# one_hot_encoder = OneHotEncoder(categories='auto')
# labels = np.array(labels).reshape(-1, 1)
# input_labels = one_hot_encoder.fit_transform(labels).toarray()

# print('Labels:\n',labels.T)
# print('One-hot encoded labels:\n',input_labels.T)


# one-hot encode labels
from sklearn.preprocessing import OneHotEncoder
labels = Y_train

one_hot_encoder = OneHotEncoder(categories='auto')
labels = np.array(labels).reshape(-1, 1)
input_labels = one_hot_encoder.fit_transform(labels).toarray()

print('Labels:\n',labels.T)
print('One-hot encoded labels:\n',input_labels.T)

Labels:
 [[1 1 1 ... 1 1 0]]
One-hot encoded labels:
 [[0. 0. 0. ... 0. 0. 1.]
 [1. 1. 1. ... 1. 1. 0.]]


In [ ]:
import pandas as pd



# Convert data type to int8
y_train = Y_train.astype('int8')

# Convert to numpy array and reshape
labels_2d = y_train.values.reshape(-1, 1)
labels_2d

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [0]], dtype=int8)

In [13]:
# save data + labels in npz int8
encoded_sequences_int8 = encoded_sequences.astype(np.int8)
input_labels_int8 = input_labels.astype(np.int8)
np.savez("/home/ndo/bash_output/encoded_sequences/onehot_endcoding.npz", encoded_sequences=encoded_sequences_int8, input_labels=input_labels_int8, labels_2d=labels_2d) 